### ISSUE TITLE
 Pest and Disaster Management in Crop Farming

### ISSUE THREAD

**Issue by riyasachdeva04** [abhijeet141/CropForesight_BackEnd#11]
I would like to enhance the existing crop prediction model by integrating pest management capabilities. The model already utilizes data and environmental factors for crop prediction, but now we aim to leverage the Gaussian Naïve Bayes algorithm to analyze and predict the likelihood of pest outbreaks and potential crop disasters based on various input parameters.

Feature Engineering and Selection:

Identify key features that are influential in predicting pest occurrences and crop disasters, such as weather conditions, soil properties, and previous pest and disease records.
Perform feature engineering techniques to extract useful information from the selected features, such as calculating aggregate statistics or deriving new features.

**Comment by riyasachdeva04** [comment]
I would like to work on this under GSSOC'23

**Comment by abhijeet141** [comment]
Hi @riyasachdeva04 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
