### ISSUE TITLE
Add the black linter workflow 

### ISSUE THREAD

**Issue by metabiswadeep** [abhijeet141/CropForesight_BackEnd#15]
Add the black linter to ensure proper and uniform linting of the codebase. As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using the black linter in GitHub actions.

I would like to work on this as a part of GSSoC 23.

**Comment by abhijeet141** [comment]
Hi @metabiswadeep 
Thank you for creating the issue. Please go ahead and start working on it. If you have any questions or need assistance during the process, feel free to ask.

Thank you for your contribution, and I'm excited to see your progress in resolving the issue.
