### ISSUE TITLE
Improvement in main.py

### ISSUE THREAD

**Issue by okaditya84** [abhijeet141/CropForesight_BackEnd#3]
Adding error handling statements and logging for better understanding at the backend for errors and keeping track of requests and other important thing.

Moreover storing the features in a variable first to make it more understandable for editing.

**Comment by abhijeet141** [comment]
Hi @okaditya84 
Thank you for creating the issue. I have reviewed it, and it looks like a great opportunity to contribute. While we don't have a formal assignment process in place at the moment, you can definitely start working on it. 

If you have any questions or need any assistance along the way, please don't hesitate to ask.

Thank you for your contribution, and I look forward to seeing your progress on resolving the issue.

**Comment by okaditya84** [comment]
> Hi @okaditya84 Thank you for creating the issue. I have reviewed it, and it looks like a great opportunity to contribute. While we don't have a formal assignment process in place at the moment, you can definitely start working on it.
> 
> If you have any questions or need any assistance along the way, please don't hesitate to ask.
> 
> Thank you for your contribution, and I look forward to seeing your progress on resolving the issue.

kindly add a gssoc23 label to my pull request that I have made.
