### ISSUE TITLE
Creating ML Model with accuracy Matrics

### ISSUE THREAD

**Issue by dhruvsaxena11** [abhijeet141/CropForesight_BackEnd#7]
@abhijeet141 Hi Sir,

I am open source contributor and a Data Science enthusiast. 
Plz kindly assign me with this issue to create the best ML Model for the dataset and accuracy matrices analysis.

Thank you 
Dhruv Saxena

**Comment by abhijeet141** [comment]
Hi @dhruvsaxena11 
Thank you for creating the issue. However, after careful consideration, I believe that our model's current accuracy of 99% is already quite high and meets our requirements. If you have any other issues or suggestions related to the project, I would be more than happy to consider them and collaborate on those.
